apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: mattfeng/kubia:0.1.0
          ports:
            - containerPort: 8080
