apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
    - image: nginx:alpine
      name: web
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
    - image: mattfeng/fortune:env
      name: html-generator
      env:
        - name: INTERVAL
          value: "30"
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
  volumes:
    - name: html
      emptyDir: {}
