# About:
#   - Simple Flask App: Deployment and Service
# Author:
#   - Matthew Feng
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: mattfeng/hello-flask-app
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
