apiVersion: v1
kind: Pod
metadata:
  name: load-data-pod
spec:
  containers:
    - name: ubuntu
      image: mattfeng/ubuntu-gcloud:1.0.0
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - mountPath: /data
          name: data-disk
  nodeSelector:
    node_class: prepare
  volumes:
    - name: data-disk
      gcePersistentDisk:
        pdName: deep-learning
        fsType: ext4
