apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: "mattfeng/kubia:0.1.0"
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
